services:
  mongodb:
    image: mongo:7-jammy

    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - ./mongodbData:/data/db

    networks:
      - backend
    
    restart: always




networks:
  backend: